apps/usuarios/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = "usuarios"

urlpatterns = [
	path('registro/', views.RegistroUsuario.as_view(), name='registro'),
]

tiendavirtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index, name='index'),
    path('Login' , auth.LoginView.as_view(template_name="usuarios/login.html") , name='login'),
    path('Logout' , auth.LogoutView.as_view() , name='logout'),

    path('usuarios/', include('apps.usuarios.urls')),

]

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# universidades = [
#     ('UNNE', 'unne.'),
#     ('UTN', 'utn'),
#     ('UNCAUS', 'uncaus'),
#    ]

class Usuario(AbstractUser):

    provincia = models.CharField(max_length=30, null=True)
    ciudad = models.CharField(max_length=30, null=True)
    # universidad = models.CharField(max_length=50,  choices=universidades)
    domicilio = models.CharField(max_length=50, null=True)
    # imagen_profile = models.ImageField(upload_to='userProfile', null = True,blank=True)
    pass

apps/usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from .models import Usuario

class RegistroUsuarioForm(UserCreationForm):
	
	class Meta:
		model = Usuario
		fields = ['username',
				'first_name',
				'last_name',
				'domicilio',				
				'password1',
				'password2',
				'email',
				'provincia',
				'ciudad',
				]
		help_texts = {
				'username': None,
				'password1': None,
				'password2': None,
			}

apps/usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from .forms import RegistroUsuarioForm
from .models import Usuario
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate

# Create your views here.
class RegistroUsuario(CreateView):
	model = Usuario
	form_class = RegistroUsuarioForm
	template_name = 'usuarios/registro.html'
	success_url = reverse_lazy('index')

	def form_valid(self, form):
		'''
		En este parte, si el formulario es valido guardamos lo que se obtiene de él y 
		usamos authenticate para que el usuario incie sesión luego de haberse registrado 
		y lo redirigimos al index
		'''

		form.save()
		usuario = form.cleaned_data.get('username')
		password = form.cleaned_data.get('password1')
		usuario = authenticate(username=usuario, password=password)
		login(self.request, usuario)
		return redirect('/')

tiendavirtual/views.py
from django.shortcuts import render, redirect

def Index(request):
	return render(request, 'index.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

<script type="text/javascript">
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>



</head>
<body>

<nav class="navbar navbar-expand-sm navbar-light" style="background-color: #e3f2fd;">

  <a class="navbar-brand" href="#">Mi Tienda Virtual</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}" data-toggle="tooltip" data-placement="bottom" title="Home">
        <img src="{% static 'ico/home.png' %}" width="20" height="20" alt="home-icon" /><span class="sr-only">(current)</span></a>
      </li>
      {% if not user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}" data-toggle="tooltip" data-placement="bottom" title="Login"><img src="{% static 'ico/user.png' %}" width="20" height="20" alt="user-login" /></a>  
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'usuarios:registro' %}" data-toggle="tooltip" data-placement="bottom" title="Registrarse"><img src="{% static 'ico/signup.png' %}" width="20" height="20" alt="user-signup" /></a>
      </li>
      </ul>
    {% else %}
    <span class="navbar-text">
		Hola, {{user.username}}
		</span>
		
    	<ul class="navbar-nav mr-auto">
    	
      	<li class="nav-item ">
       		<a class="nav-link" href="{% url 'logout' %}" data-toggle="tooltip" data-placement="bottom" title="Salir"><img src="{% static 'ico/logout.png' %}" width="20" height="20" alt="user-login" /></a>
      	</li>
     	</ul>		
 
    	{% endif %}
  </div>
</nav>


<div class="row">
  <div class="col col-lg-2">
    <div id="panel-lateral" class="col" style="background-color: blue">
          <ul>
            <li>elemento </li>
            <li>elemento </li>
            <li>elemento </li>
            <li>elemento </li>
          </ul>
      </div>
    </div>
   
  <div class="col-8">
    {% block contenido %}

{% endblock contenido %}
  </div>
</div>


<!-- <ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Disabled</a>
  </li>
</ul>   -->



</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

<div class="col-sm-8">col-sm-8
	this is index<br>
	</div>
		

{% endblock contenido %}

templates/usuarios/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block contenido %}

<!-- Modal -->
<form method="POST"> {% csrf_token %}
<div class="modal fade" id="basicExampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ingreso de Usuarios</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <table border="1">
          {{form.errors}}
          {{ form | crispy }}
         </table>
      </div>
      <div class="modal-footer">
        
        <button type="button" onclick="history.back()" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Ingresar</button>
      </div>
    </div>
  </div>
</div>
	        
        
    </form>


    <script>
      $(document).ready(function()
      {
         $("#basicExampleModal").modal("show");
      });
</script>
{% endblock contenido %}

 

templates/usuarios/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<form method="POST"> {% csrf_token %}

          <table border="1">
          
          {{ form }}
         </table>
     
        
        <button type="submit" class="btn btn-primary">Ingresar</button>
   
	        
        
    </form>

</body>
</html>